import { getPage } from "../utils/browser.js";
import { runAxe } from "../utils/axeRunner.js";
import { findMissingAltText } from "./altText.js";
import { checkHeadingStructure } from "./headingCheck.js";

export async function generateAdaReport(params: {
  url: string;
  format?: "markdown" | "json";
}): Promise<string> {
  const { url, format = "markdown" } = params;
  const { page, close } = await getPage(url);

  try {
    const axeResult = await runAxe(page, { wcagLevel: "wcag2aa" });

    const score = Math.max(
      0,
      Math.round(
        100 - axeResult.violations.length * 5 - 
        axeResult.violations.filter((v) => v.impact === "critical").length * 10
      )
    );

    const scoreGrade =
      score >= 90 ? "A" : score >= 75 ? "B" : score >= 60 ? "C" : score >= 40 ? "D" : "F";

    const criticalCount = axeResult.violations.filter((v) => v.impact === "critical").length;
    const seriousCount = axeResult.violations.filter((v) => v.impact === "serious").length;
    const moderateCount = axeResult.violations.filter((v) => v.impact === "moderate").length;
    const minorCount = axeResult.violations.filter((v) => v.impact === "minor").length;

    if (format === "json") {
      return JSON.stringify(
        {
          url,
          timestamp: axeResult.timestamp,
          score,
          grade: scoreGrade,
          summary: {
            totalViolations: axeResult.violations.length,
            critical: criticalCount,
            serious: seriousCount,
            moderate: moderateCount,
            minor: minorCount,
            passed: axeResult.passes,
            incomplete: axeResult.incomplete,
          },
          violations: axeResult.violations,
        },
        null,
        2
      );
    }

    // Markdown report
    let report = `# ♿ ADA/WCAG Accessibility Report\n\n`;
    report += `**URL:** ${url}  \n`;
    report += `**Date:** ${axeResult.timestamp}  \n`;
    report += `**Standard:** WCAG 2.1 AA  \n\n`;
    report += `---\n\n`;

    report += `## 🎯 Accessibility Score: ${score}/100 (Grade: ${scoreGrade})\n\n`;

    const bar = "█".repeat(Math.round(score / 10)) + "░".repeat(10 - Math.round(score / 10));
    report += `\`${bar}\` ${score}%\n\n`;

    report += `## 📊 Summary\n\n`;
    report += `| Severity | Count |\n|---|---|\n`;
    report += `| 🔴 Critical | ${criticalCount} |\n`;
    report += `| 🟠 Serious  | ${seriousCount} |\n`;
    report += `| 🟡 Moderate | ${moderateCount} |\n`;
    report += `| 🔵 Minor    | ${minorCount} |\n`;
    report += `| ✅ Passed   | ${axeResult.passes} |\n\n`;

    if (axeResult.violations.length === 0) {
      report += `## ✅ No Violations Found!\n\nThis page meets WCAG 2.1 AA standards.\n`;
    } else {
      report += `## 🚨 Violations (${axeResult.violations.length})\n\n`;
      axeResult.violations.forEach((v, i) => {
        report += `### ${i + 1}. [${(v.impact ?? "unknown").toUpperCase()}] \`${v.id}\`\n\n`;
        report += `**Issue:** ${v.help}  \n`;
        report += `**WCAG Reference:** [${v.id}](${v.helpUrl})  \n`;
        report += `**Affected elements:** ${v.nodes.length}  \n\n`;
        if (v.nodes[0]) {
          report += `**Example element:**\n\`\`\`html\n${v.nodes[0].html.substring(0, 200)}\n\`\`\`\n\n`;
          report += `**How to fix:** ${v.nodes[0].failureSummary}\n\n`;
        }
        report += `---\n\n`;
      });
    }

    report += `## 💡 Quick Wins\n\n`;
    if (criticalCount > 0) report += `- Fix all **critical** violations first — these block screen reader users completely\n`;
    if (seriousCount > 0) report += `- Address **serious** violations next — major barriers for assistive technology users\n`;
    report += `- Run this audit after every major release\n`;
    report += `- Test with real screen readers (NVDA/VoiceOver) for complete validation\n\n`;

    report += `---\n*Generated by [playwright-ada-mcp](https://github.com/deeksithaa/playwright-ada-mcp)*\n`;

    return report;
  } finally {
    await close();
  }
}
